### ISSUE TITLE
Improve calculation of required scrolling offset for large multiline UITextViews

### ISSUE THREAD

**Issue by andriichernenko** [shapehq/SHPKeyboardAwareness#8]
Currently the calculated amount of scroll for `UITextView` seems to be equal to the keyboard height, just like for other views:
![demo1](https://cloud.githubusercontent.com/assets/4421971/15411734/3e6a3752-1e22-11e6-8fab-9bff8b3590b7.gif)

It does not look nice for long text views, and in some cases it can lead to cursor being pushed offscreen (and then returned back by UIKit):
![demo2](https://cloud.githubusercontent.com/assets/4421971/15411740/44d86e24-1e22-11e6-95bf-ee382f12813b.gif)

I think it would be much better to scroll it just enough to keep the cursor above the keyboard (with some slight offset).

Note: never mind choppy animations on the demos. Everything animates fine on device.

**Comment by jakovi89** [comment]
Should be solved with the 3.0.0 update, the default behaviour is to look for the caret in the textfield and calculate the offset based on that.
Thanks for the suggestion
